version: '3'
services:
   web:
     build:
       context: ../src
       args:
         GITHUB_USERNAME: $GITHUB_USERNAME
         GITHUB_PERSONAL_ACCESS_TOKEN: $GITHUB_PERSONAL_ACCESS_TOKEN
       dockerfile: ../docker/Dockerfile
     ports:
       - "3000:3000"