version: '3'
services:
   web:
     build:
       context: ../src
       secrets:
         - GITHUB_USERNAME
         - GITHUB_PERSONAL_ACCESS_TOKEN
       dockerfile: ../docker/Dockerfile
     ports:
       - "3000:3000"
secrets:
  GITHUB_USERNAME:
    environment: GITHUB_USERNAME
  GITHUB_PERSONAL_ACCESS_TOKEN:
    environment: GITHUB_PERSONAL_ACCESS_TOKEN