# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

namespace :dev do
    desc 'Format check'
    task :lint do
      sh 'bundle exec rubocop'
    end
    namespace :lint do
      desc 'Format fix'
      task :fix do
        sh 'bundle exec rubocop -A'
      end
    end
  end
