name: BuildImage
run-name: "Build Image run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    workflow_call:
    workflow_dispatch:
jobs:
    build-image:
        runs-on: ubuntu-latest
        environment: production
        env:
            APP_VERSION: ${{ github.sha }}
            DOCKER_IMAGE: hello-world-hex-ruby-web-rails
            GITHUB_USERNAME: ${{ vars.ENV_GITHUB_USERNAME }}
            GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.ENV_GITHUB_PERSONAL_ACCESS_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build Docker image
              run: |
                docker build \
                  -f ./docker/Dockerfile \
                  -t $DOCKER_IMAGE:$APP_VERSION \
                  --secret id=github-username,env=GITHUB_USERNAME \
                  --secret id=github-personal-access-token,env=GITHUB_PERSONAL_ACCESS_TOKEN \
                  ./src
            - name: Push to ECR
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
                docker tag $DOCKER_IMAGE:$APP_VERSION ${{ secrets.ECR_REGISTRY }}:$APP_VERSION
                docker push ${{ secrets.ECR_REGISTRY }}:$APP_VERSION