name: CI-CD
run-name: "CI-CD run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:
concurrency:
    group: ci-cd ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    ci:
        permissions:
          contents: read
        secrets: inherit
        uses: ./.github/workflows/ci.yml

    cd:
        permissions:
            contents: read
            packages: write
        secrets: inherit
        uses: ./.github/workflows/cd.yml
        needs: ci