name: CI
run-name: "CI run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_call:
    workflow_dispatch:
concurrency:
    group: ci ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    static-code-analysis:
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/static-code-analysis.yml
    functional-tests:
        needs: static-code-analysis
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/functional-tests.yml
    security-tests:
        needs: static-code-analysis
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/security-tests.yml
    build-image:
        needs: [functional-tests,security-tests]
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/build-image.yml