name: SecurityTests
run-name: "Security Tests run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    workflow_call:
    workflow_dispatch:
jobs:
    static-security-tests:
        runs-on: ubuntu-latest
        environment: production
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '3.3.5'
                  bundler-cache: true
            - name: Install dependencies
              env:
                GITHUB_USERNAME: ${{ vars.ENV_GITHUB_USERNAME }}
                GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.ENV_GITHUB_PERSONAL_ACCESS_TOKEN }}
              run: |
                gem install bundler
                cd ./src
                bundle install --with test
            - name: Static Application Security Test (SAST) - Talisman - Detect secrets in commits
              uses: carhartl/talisman-secrets-scan-action@v1.4.0
            - name: Static Application Security Test (SAST) - Brakeman - Analyze Ruby on Rails code for potential security vulnerabilities
              run: |
                cd ./src
                brakeman . -f html -o sast-brakeman-report.html
            - name: Upload Static Application Security Test (SAST) - Brakeman Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: sast-brakeman-report
                  path: src/sast-brakeman-report.html
            - name: Security Composition Analysis (SCA) - OWASP Dependency Check
              uses: dependency-check/Dependency-Check_Action@main
              with:
                      project: 'hello_world_hex_ruby__web_rails'
                      path: './src'
                      format: 'HTML'
                      out: 'dependency-check'
            - name: Upload OWASP Dependency Check Report
              uses: actions/upload-artifact@v4
              with:
                      name: dependency-check
                      path: ${{github.workspace}}/src/dependency-check