name: StaticCodeAnalysis
run-name: "Static Code Analysis run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    workflow_call:
    workflow_dispatch:

jobs:
    linting:
        runs-on: ubuntu-latest
        environment: production
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '3.3.5'
                  bundler-cache: true
            - name: Install dependencies
              env:
                GITHUB_USERNAME: ${{ vars.ENV_GITHUB_USERNAME }}
                GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.ENV_GITHUB_PERSONAL_ACCESS_TOKEN }}
              run: |
                echo $GITHUB_USERNAME
                gem install bundler
                cd ./src
                bundle install
            - name: Linting
              run: |
                  cd ./src
                  bundle exec rake dev:lint